FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN sed -i 's/\r$//' start-dev.sh && chmod +x start-dev.sh

RUN npx prisma generate

EXPOSE 3001

CMD ["/bin/bash", "./start-dev.sh"]
